# environment_win_full.yml
name: radiacuda
channels:
  - conda-forge
  - nvidia
  - nodefaults
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - scipy
  - fftw
  - cmake>=3.28
  - ninja
  - setuptools
  - scikit-build-core
  - intel-openmp
  - cupy
  - cuda-toolkit=12.6
  - gmsh>=4.15
  - python-gmsh
  - yaml
  - pyyaml
  - mpi4py
  - sympy
  - tqdm
  - impi-devel
  - h5py
  - cython
  - intel-opencl-rt
  - meshio
  - numba
  - occt
  - pyopencl
  - pythonocc-core
  - rtree
  - trimesh
  - pyamg
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - warp-lang
    - bempp-cl
    - numpy-quaternion
